name: Run Tests

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  test:
    name: Test code
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.24"
      
      - name: Verify Dependencies
        run: go mod tidy && git diff --exit-code

      - name: Run Tests
        run: go test $(go list ./... | grep -v /examples/) -v

      - name: Run race detector
        run: go test -race $(go list ./... | grep -v /examples/)